### ISSUE TITLE
0.5.0 checklist

### ISSUE THREAD

**Issue by rewrking** [chalet-org/chalet#183]
At the time of release, do in order:
- [x] Write Contributing doc, make note of it in Readme
- [x] Remove "Build from Source" contents from Readme, point to COMPILE.md
- [x] Update Chalet version, build & tag latest Chalet release
- [x] Update Release notes
- [x] In `CustomMarkdownParser.ts:201`, make sure `getChaletFile` points to latest tag, not `main`
- [x] Push website update
- [x] Push extension update

**Comment by rewrking** [comment]
It's out!
